In [12]:
import sys
sys.path.append("../PyFiles/")

In [13]:
# Library Imports
import pandas as pd
import os

In [14]:
# Package Imports
import configs as cf
from logger import App_Logger
from data_loader_train import Data_Loader
from project_gen import Create_Project

In [15]:
# Instantiate the logger object
logger_object = App_Logger()

# Create an instance of the Create_Project class
project_instance = Create_Project(logger_object)

# Call the initiate_project method on the instance
project_id = project_instance.initiate_project()
project_id

'20240310214949'

In [16]:
# Open a file for logging in append mode to prevent overwriting
file_object = open(os.path.join(cf.FILE_PATH, cf.output_files, project_id, 'Logs', 'Global_Logs.txt'), "a")

inp_file = r"C:\Users\mnsnn\Downloads\ThyroidDetection (1)\ThyroidDetection\code\Thyroid_Detection\Training_FileFromDB\InputFile.csv"
# Now, you can pass file_object to Data_Getter and it will remain open
data_getter = Data_Loader(file_object, logger_object, inp_file)
display(data_getter.load_data())

# Remember to close the file manually when you're done
# file_object.close()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,...,TT4_measured,TT4,T4U_measured,T4U,FTI_measured,FTI,TBG_measured,TBG,referral_source,Class
0,41,F,f,f,f,f,f,f,f,f,...,t,125,t,1.14,t,109,f,?,SVHC,negative
1,23,F,f,f,f,f,f,f,f,f,...,t,102,f,?,f,?,f,?,other,negative
2,46,M,f,f,f,f,f,f,f,f,...,t,109,t,0.91,t,120,f,?,other,negative
3,70,F,t,f,f,f,f,f,f,f,...,t,175,f,?,f,?,f,?,other,negative
4,70,F,f,f,f,f,f,f,f,f,...,t,61,t,0.87,t,70,f,?,SVI,negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3767,30,F,f,f,f,f,f,f,f,f,...,f,?,f,?,f,?,f,?,other,negative
3768,68,F,f,f,f,f,f,f,f,f,...,t,124,t,1.08,t,114,f,?,SVI,negative
3769,74,F,f,f,f,f,f,f,f,f,...,t,112,t,1.07,t,105,f,?,other,negative
3770,72,M,f,f,f,f,f,f,f,f,...,t,82,t,0.94,t,87,f,?,SVI,negative
3771,64,F,f,f,f,f,f,f,f,f,...,t,99,t,1.07,t,92,f,?,other,negative